### ISSUE TITLE
Doesn't compile with ghc 8.0.1

### ISSUE THREAD

**Issue by ghost** [jaspervdj/websockets-snap#17]
I installed the git version of websockets, but when I tried to compile websockets-snap I got:

`[1 of 1] Compiling Network.WebSockets.Snap ( src/Network/WebSockets/Snap.hs, dist/build/Network/WebSockets/Snap.o )

src/Network/WebSockets/Snap.hs:131:9: error:
    • Couldn't match expected type ‘io-streams-1.3.5.0:System.IO.Streams.Internal.OutputStream
                                      Data.ByteString.Builder.Internal.Builder
                                    -> IO ()’
                  with actual type ‘E.Iteratee ByteString IO ()’

`

Best wishes,
Henry Laxen

**Comment by henrylaxen** [comment]
I forgot to mention I changed:
`    snap-core     >= 0.8,
    snap-server   >= 0.8,
    websockets    >= 0.9.5
`

**Comment by jaspervdj** [comment]
It seems like you are also relying on a still unreleased version of `snap`. I will try and fix these issues when the packages are released but it's hard to do with a bunch of git versions...
